name: titancast
description: "Universal Smart TV Remote Control Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.0
  speech_to_text: ^7.0.0
  flutter_adb: ^0.1.1
  # UI
  cupertino_icons: ^1.0.8

  # Crypto (Digest Auth for Philips Android TV)
  crypto: ^3.0.3

  # Network
  http: ^1.2.0
  web_socket_channel: ^3.0.1
  xml: ^6.3.0
  connectivity_plus: ^7.0.0
  network_info_plus: ^7.0.0
  multicast_dns: ^0.3.2+4
  permission_handler: ^12.0.1

  # Scanner
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
